services:
  app:
    build: .
    volumes:
      - .:/app
      #oque esta do lado direito representa minha pasta, atual, oque esta do lado esquerdo representa a pasta para onde os arquivos serao compartilhados/copiados dentro do container.
    working_dir: /app
    command: sleep infinity
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
  db:
    image: mariadb:11.4
    container_name: segup-db
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - segup-db-data:/var/lib/mysql

volumes:
  segup-db-data:




#comandos para acessar o container
#docker compose exec app sh